[workspace]
authors   = ["zaynram <ramdasszayn@gmail.com>"]
channels  = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[dependencies]
ipykernel   = "*"
ipywidgets  = "*"
pyinstaller = "*"
python      = ">=3.13"
ramda_py    = { url = "https://github.com/zaynram/ramda-py/raw/refs/heads/master/build/ramda_py-0.1.0-pyh4616a5c_0.conda" }
tqdm        = "*"

[environments]
default = []
dev = ["dev-dependencies"]

[feature.dev-dependencies.dependencies]
pytest = "*"
black = "*"
ruff = "*"

[pypi-dependencies]
apps     = { path = "apps", editable = true }
gooey    = "*"
ollama   = ">=0.5.3, <0.6"
pydantic = "==2.12.0a1"
pymupdf  = ">=1.26.4, <2"
wxpython = "*"
# New dependencies for CLI and multi-format support
typer    = ">=0.9.0"
python-docx = "*"
docx2txt = "*"
pyyaml   = "*"
toml     = "*"
rich     = "*"

[tasks]
  [tasks.app]
  args = [{ arg = "NAME" }]
  cmd  = ["python", "{{ NAME }}.py"]
  
  [tasks.cli]
  cmd = ["python", "main.py"]
  description = "Run the Doculyze CLI application"
  
  [tasks.analyze]
  cmd = ["python", "main.py", "analyze"]
  description = "Run document analysis"
  
  [tasks.preprocess]
  cmd = ["python", "main.py", "preprocess"]
  description = "Run document preprocessing"
  
  [tasks.test]
  cmd = ["python", "main.py", "test-extract", "sample_docs/sample_contract.txt"]
  description = "Run basic functionality test"
  
  [tasks.lint]
  cmd = ["ruff", "check", "."]
  description = "Run code linting"
  env = { dev = true }
  
  [tasks.format]
  cmd = ["black", "."]
  description = "Format code with black"
  env = { dev = true }
