[workspace]
authors   = ["zaynram <ramdasszayn@gmail.com>"]
channels  = ["conda-forge"]
platforms = ["linux-64", "win-64"]
preview   = ["pixi-build"]

[dependencies]
ipykernel   = "*"
ipywidgets  = "*"
pyinstaller = "*"
python      = ">=3.13"
rampy       = { git = "https://github.com/zaynram/ramda-py" }
tqdm        = "*"

[environments]
default = []

[pypi-dependencies]
apps     = { path = "apps", editable = true }
gooey    = "*"
ollama   = ">=0.5.3, <0.6"
pydantic = "==2.12.0a1"
pymupdf  = ">=1.26.4, <2"
wxpython = "*"

[tasks]
  [tasks.app]
  args = [{ arg = "NAME" }]
  cmd  = ["python", "{{ NAME }}.py"]
