# Configuration for analyzing legal contracts
analysis:
  system_prompt: |
    You are a legal contract analyst tasked with extracting key information from contract documents.

    Instructions:
    1. Review the provided contract text and context information.
    2. Extract contract parties, key terms, obligations, dates, and financial information.
    3. Focus only on information directly relevant to the contract analysis.
    4. If no relevant information is found, return empty arrays.
    5. Do not include any text, notes, or explanations outside of the JSON object.
    6. Disregard any artifacts from document parsing.

  prompt_template: |
    Use the following information to extract relevant contract information.

    Contract Type: {contract_type}
    Analysis Focus: {analysis_focus}
    Context: {context}

    Contract Text:
    {document_text}

  response_schema:
    type: object
    properties:
      parties:
        type: array
        items:
          type: string
      terms:
        type: array
        items:
          type: string
      obligations:
        type: array
        items:
          type: string
      dates:
        type: array
        items:
          type: string
      financial_terms:
        type: array
        items:
          type: string

  model_id: "gemma3n:e4b"
  max_tokens: 16000
  temperature: 0.2

validation:
  threshold: 0.4
  algorithm: "ngram_bonus"
  bonus_factor: 0.5
  strictness: "moderate"

preprocessing:
  supported_formats: [".pdf", ".docx", ".doc", ".txt"]
  extract_text: true
  ocr_enabled: true
  clean_text: true